--- Drop all existing tables ---
CREATE DATABASE IF NOT EXISTS BOOKS;
CREATE USER 'USER1'@'localhost' IDENTIFIED BY 'USER1PASSWORD';
GRANT ALL PRIVILEGES ON BOOKS.* TO 'USER1'@'localhost';    

DROP TABLE IF EXISTS title;
DROP TABLE IF EXISTS year;
DROP TABLE IF EXISTS price;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS author;

